services:

  products-db:
    image: postgres:15
    container_name: products-db
    environment:
      POSTGRES_DB: products_db
      POSTGRES_USER: products
      POSTGRES_PASSWORD: products
    ports:
      - "5433:5432"

  inventory-db:
    image: postgres:15
    container_name: inventory-db
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: inventory
      POSTGRES_PASSWORD: inventory
    ports:
      - "5434:5432"

  products-service:
    build: ./ProductsService
    container_name: products-service
    ports:
      - "8081:8081"
    depends_on:
      - products-db

  inventory-service:
    build: ./InventoryService
    container_name: inventory-service
    ports:
      - "8082:8082"
    depends_on:
      - inventory-db
      - products-service
